import axios from "axios"

import monAPI from "@/lib/monAPI"

import {
  SubscriptionType,
  UpgradeSubscriptionType,
  UserSubscriptionType
} from "@/schemas/subscriptionSchema"

export const getAllSubscriptions = async (): Promise<SubscriptionType[]> => {
  try {
    const response = await monAPI.get("/subscriptions")

    if (!response || !response.data) {
      throw {
        isCustomError: true,
        message:
          "Không nhận được phản hồi từ máy chủ. Có thể máy chủ đang gặp sự cố hoặc kết nối mạng của bạn bị gián đoạn"
      }
    }

    const { success, message, data } = response.data

    if (success) {
      return data as SubscriptionType[]
    } else {
      throw {
        isCustomError: true,
        message: message || "Không thể lấy danh sách gói đăng ký"
      }
    }
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      console.log("Lỗi từ server:", error.response?.data || error.message)
      throw error
    } else {
      console.log("Lỗi không phải Axios:", error)
      throw {
        isCustomError: true,
        message: "Đã xảy ra lỗi không mong muốn"
      }
    }
  }
}

export const getSubscriptionByUserId = async (
  userId: string | undefined
): Promise<UserSubscriptionType> => {
  try {
    const response = await monAPI.get(`/subscriptions/user/${userId}`)

    if (!response || !response.data) {
      throw {
        isCustomError: true,
        message:
          "Không nhận được phản hồi từ máy chủ. Có thể máy chủ đang gặp sự cố hoặc kết nối mạng của bạn bị gián đoạn"
      }
    }

    const { success, message, data } = response.data

    if (success) {
      return data as UserSubscriptionType
    } else {
      throw {
        isCustomError: true,
        message: message || "Không thể lấy thông tin gói đăng ký"
      }
    }
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      console.log("Lỗi từ server:", error.response?.data || error.message)
      throw error
    } else {
      console.log("Lỗi không phải Axios:", error)
      throw {
        isCustomError: true,
        message: "Đã xảy ra lỗi không mong muốn"
      }
    }
  }
}

export const upgradeSubscription = async (
  upgradeSubscriptionData: UpgradeSubscriptionType
): Promise<string> => {
  try {
    const response = await monAPI.post(
      `/subscriptions/upgrade`,
      upgradeSubscriptionData
    )

    if (!response || !response.data) {
      throw {
        isCustomError: true,
        message:
          "Không nhận được phản hồi từ máy chủ. Có thể máy chủ đang gặp sự cố hoặc kết nối mạng của bạn bị gián đoạn"
      }
    }

    const { success, message } = response.data

    if (!success) {
      throw {
        isCustomError: true,
        message: message || "Không thể nâng cấp gói đăng ký"
      }
    }

    console.log(message)
    return message
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      console.log("Lỗi từ server:", error.response?.data || error.message)
      throw error
    } else {
      console.log("Lỗi không phải Axios:", error)
      throw {
        isCustomError: true,
        message: "Đã xảy ra lỗi không mong muốn"
      }
    }
  }
}
